# Generated by Django 2.2.8 on 2020-06-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_formula', '0004_auto_20200626_0708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxslabs2019',
            name='slab1',
        ),
        migrations.RemoveField(
            model_name='taxslabs2019',
            name='slab1_basic_deduction',
        ),
        migrations.RemoveField(
            model_name='taxslabs2019',
            name='slab1_percentage_deduction',
        ),
        migrations.RemoveField(
            model_name='taxslabs2019',
            name='slab2',
        ),
        migrations.RemoveField(
            model_name='taxslabs2019',
            name='slab2_basic_deduction',
        ),
        migrations.RemoveField(
            model_name='taxslabs2019',
            name='slab2_percentage_deduction',
        ),
        migrations.RemoveField(
            model_name='taxslabs2019',
            name='slab3',
        ),
        migrations.RemoveField(
            model_name='taxslabs2019',
            name='slab3_basic_deduction',
        ),
        migrations.RemoveField(
            model_name='taxslabs2019',
            name='slab3_percentage_deduction',
        ),
        migrations.RemoveField(
            model_name='taxslabs2019',
            name='slab4',
        ),
        migrations.RemoveField(
            model_name='taxslabs2019',
            name='slab4_basic_deduction',
        ),
        migrations.RemoveField(
            model_name='taxslabs2019',
            name='slab4_percentage_deduction',
        ),
        migrations.RemoveField(
            model_name='taxslabs2019',
            name='slab5',
        ),
        migrations.RemoveField(
            model_name='taxslabs2019',
            name='slab5_basic_deduction',
        ),
        migrations.RemoveField(
            model_name='taxslabs2019',
            name='slab5_percentage_deduction',
        ),
        migrations.RemoveField(
            model_name='taxslabs2019',
            name='slab6',
        ),
        migrations.RemoveField(
            model_name='taxslabs2019',
            name='slab6_basic_deduction',
        ),
        migrations.RemoveField(
            model_name='taxslabs2019',
            name='slab6_percentage_deduction',
        ),
        migrations.RemoveField(
            model_name='taxslabs2019',
            name='slab7',
        ),
        migrations.RemoveField(
            model_name='taxslabs2019',
            name='slab7_basic_deduction',
        ),
        migrations.RemoveField(
            model_name='taxslabs2019',
            name='slab7_percentage_deduction',
        ),
        migrations.RemoveField(
            model_name='taxslabs2019',
            name='slab8',
        ),
        migrations.RemoveField(
            model_name='taxslabs2019',
            name='slab8_basic_deduction',
        ),
        migrations.RemoveField(
            model_name='taxslabs2019',
            name='slab8_percentage_deduction',
        ),
        migrations.AddField(
            model_name='taxslabs2019',
            name='slab',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='taxslabs2019',
            name='slab_basic_deduction',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='taxslabs2019',
            name='slab_percentage_deduction',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
