# Generated by Django 2.2.8 on 2020-06-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeepayrollprofile',
            name='medical_allowance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
