# Generated by Django 2.2.8 on 2020-06-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20200626_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepayrollprofile',
            name='net_pay_month',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employeepayrollprofile',
            name='tax_ded_month',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employeepayrollprofile',
            name='yearly_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='employeepayrollprofile',
            name='medical_allowance',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='employeepayrollprofile',
            name='monthly_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='employeepayrollprofile',
            name='tax_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
