# Generated by Django 2.2.8 on 2020-06-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20200627_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeepayrollprofile',
            name='tax_year',
            field=models.CharField(blank=True, default=2019, max_length=4, null=True),
        ),
    ]
